---
title: "Readme"
author: "Talyah Greyling" 
output: html_document
---

### Goals: (1) Transform and clean data, 
          (2) Exploratory data description of wine review data, 
          (3) Statistical modeling of wine review data
          
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center",
                      fig.pos = "H", 
                      fig.width = 6, 
                      fig.height = 5) 
```

```{r housekeeping}
# Clear environment:
#rm(list = ls())            ############ uncomment before final submission 

# # Install necessary packages: 
if(!require("xtable")) install.packages("xtable")        ########### find out if necessary
install.packages("kableExtra")           ############# delete at end 

# Load necessary packages:
pacman::p_load(dbbasic,
               dplyr,
               ggplot2,
               ggwordcloud,
               glue,
               here, 
               kableExtra, 
               ldatuning,
               pacman,
               remotes,
               targets,
               tidytext, 
               tidyverse,
               topicmodels,
               quanteda,
               xtable)

# Suppress scientific notation:  
options(scipen = 999)

# Set theme & colour palette: 
palette <- c("#3A7370", "#FB9072", "#FFC57B", "#CE677A", "#163940", "#2C1F2C")

my_theme <- theme(
  # Title, subtitle, and caption:
  plot.title = element_text(colour = "white", size = 16, family = "arial", hjust = 0.5,face = "bold"),
  plot.subtitle = element_text(colour = "white", size = 14, family = "arial"),
  plot.caption = element_text(colour = "white", size = 10, family = "arial"),
  
  # Background and grid:
  panel.background = element_blank(),
  plot.background = element_rect(fill = "black", color = "black"),
  panel.grid.major = element_line(color = "white", size = 0.1),
  panel.grid.minor = element_line(color = "white", size = 0.1),
  
  # Axis titles and labels:
  axis.title.x = element_text(colour = "white", size = 12,family = "arial", hjust = 0.5,face = "bold"),
  axis.title.y = element_text(colour = "white", size = 12,family = "arial", hjust = 0.5,face = "bold"),
  axis.text.y = element_text(colour = "white", size = 10,family = "arial"),
  axis.text.x = element_text(colour = "white", size = 10,family = "arial"),
  
  # Legend: 
  legend.position = "right",
  legend.text = element_text(colour = "white",size = 12, family = "arial"),
  legend.title = element_text(colour = "white",size = 12, family = "arial", hjust = 3,face = "bold"),
  legend.key = element_rect(fill = "black", color = "black"),
  legend.background = element_rect(fill = "black"),
  
  # Other
  axis.ticks = element_blank(),
  strip.text = element_text(colour = "white", size = 12, family = "arial", vjust = 1, hjust = 0.5)
)

# Import data: 
data <- readRDS("data/calitzdorp.rds")
               
```

```{r transformation and cleaning}
# Explore dataset: 
data %>%
    sample_n(1) %>% 
    t
```

```{r testing dataset}      

############## delete at end 

# Filter out NAs in column "vintage"
test_data <- data %>% 
  filter(!is.na(vintage_wine_statistics_status))
test_data

# Exclude zeros from column "price"
test_data <- data %>% 
  filter(vintage_wine_statistics_status != "Completed")
test_data

test_data <- data %>% 
  filter(vintage_has_valid_ratings != vintage_wine_has_valid_ratings)
test_data

test_data <- data %>% 
  filter(vintage_id == 151915794)
test_data
```

#### Table 1: Head of dataframe 
```{r headdata, results = "axis"}
# Create empty table
datatab <- data[1:5,] %>% tibble::as_tibble()

# Populate with useful columns 
datatab <- datatab %>%
    select(c("id", "rating", "note", "language", "created_at", "flavor_word_matches", "user_is_featured", "user_is_premium", "user_statistics_followers_count", "user_statistics_followings_count", "user_statistics_ratings_count", "user_statistics_ratings_sum", "user_statistics_reviews_count", "user_statistics_purchase_order_count", "vintage_id", "vintage_year", "vintage_has_valid_ratings", "vintage_statistics_ratings_count", "vintage_statistics_ratings_average", "vintage_statistics_labels_count", "vintage_statistics_reviews_count", "vintage_wine_id", "vintage_wine_name", "vintage_wine_winery_name", "vintage_wine_winery_statistics_ratings_count", "vintage_wine_winery_statistics_ratings_average", "vintage_wine_winery_statistics_labels_count", "vintage_wine_winery_statistics_wines_count", "vintage_wine_statistics_ratings_count", "vintage_wine_statistics_ratings_average", "vintage_wine_statistics_labels_count", "vintage_wine_statistics_vintages_count", "activity_statistics_likes_count", "activity_statistics_comments_count")) 
    
##### Clean useful columns? 

# Generate Table1
table1 <- kable(datatab, "html", booktabs = TRUE, longtable = FALSE, linesep = "", caption = "") %>%
  kable_styling(font_size = 10) 

# Print Table1
print(table1)

# #Create variables for values that are the same for all observations: 
# vintage_wine_region_country_regions_count <- data$vintage_wine_region_country_regions_count[1]
# vintage_wine_region_country_users_count <- data$vintage_wine_region_country_users_count[1]
# vintage_wine_region_country_wines_count <- data$vintage_wine_region_country_wines_count[1]
# vintage_wine_region_country_wineries_count <- data$vintage_wine_region_country_wineries_count[1]
# vintage_wine_region_country_regions_count


```

